settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: day18-part2
  path: .
  commands:
    vet:
      status: true
    fmt:
      status: true
    install:
      status: true
    test:
      status: true
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
